development: 
  adapter: postgresql
  database: sampledb
  password: md5574a71crails s72b114546ec3e5663914dc67c
  pool: 5
  timeout: 5000
  username: P
  host: localhost
  port: 5432

production: 
  adapter: postgresql
  database: sampledb
  pool: 5
  timeout: 5000

test: 
  adapter: postgresql
  database: sampledb
  pool: 5
  timeout: 5000