

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: sampledb

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
